### PR TITLE
Blcrs

### PR DESCRIPTION
**Pull request by Conorc1000**

### CODE REVIEW

**Comment by nelsonic** [comment]
This code looks good. 
there are merge issues because the Master branch has diverged. I will attempt to fix those conflicts so we can get this PR merged. :+1:

**Comment by des-des** [comment]
atm the server built to serve form then save input as md file to fs not integrated with md-amp conversion. I figure this can wait till after ampl..

**Comment by nelsonic** [comment]
@des-des you're a *magician*! :wink:

**Comment by nelsonic** [comment]
Looks great Team BLCRS! :star2: 
Thanks again @des-des for resolving the merge conflicts. :+1: 
Onto ***Phase Two***! :wink:

**Pull request merged**
