### PR TITLE
Heroku

### PR DESCRIPTION
**Pull request by jackcarlisle**
Changing endpoint in server.js to enable us to deploy our branch to heroku #24 #37

### CODE REVIEW

**Comment by nelsonic** [comment]
@jackcarlisle *always* have a `root` handler for your apps...
heroku-404

**Comment by des-des** [comment]
@nelsonic working now? 
image

**Comment by hdrdavies** [comment]
very good @des-des

**Comment by nelsonic** [comment]
@des-des :+1: 
Now you "*just*" need to spend the rest of the day making it *look* the part. :wink: 
Hope the morning is going well.

**Pull request merged**
